# 1. autoregressive with sequence info

In [78]:
import torch

# data = torch.load('/home/junjiechen/1_work/original_soft/LigandMPNN/outputs/autoregressive_score_w_seq/1BC8_1.pt')
data = torch.load('/home/junjiechen/1_work/250401-Dpepalign/Benchmark-Filter/Output/5onp-merged/ligandmpnn_v_32_020_25/score_0.1/5onp_1.pt')

In [ ]:
data['log_probs'][1][0] # batch1的第一号位置的所有残基的log probes,按照alphabet顺序排列

array([-1.5815789, -4.1681585, -2.0288978, -2.6399355, -5.1741757,
       -3.7712731, -4.394065 , -5.250885 , -3.3111138, -4.9004493,
       -4.8424473, -2.4963813, -3.7008572, -2.8999667, -2.797594 ,
       -1.640079 , -3.2359614, -5.010689 , -5.517965 , -4.9840374,
       -5.506802 ], dtype=float32)

In [80]:
data['native_sequence']



array([15,  5, 16,  7,  5], dtype=int32)

In [40]:
print(s for s in data['native_sequence'])

<generator object <genexpr> at 0x7830796c57b0>


In [89]:
S_one_hot = torch.nn.functional.one_hot(torch.tensor(data['native_sequence'],dtype=torch.int64), 21).float()
S_one_hot

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.]])

In [90]:
prob_per_residue = S_one_hot * data['log_probs'][0]# 每个位置的log prob对应的残基的one hot表示相乘
prob_per_residue

tensor([[-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,
         -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -1.6401,
         -0.0000, -0.0000, -0.0000, -0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.1096, -0.0000, -0.0000,
         -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,
         -0.0000, -0.0000, -0.0000, -0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,
         -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,
         -0.9372, -0.0000, -0.0000, -0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -1.0919,
         -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,
         -0.0000, -0.0000, -0.0000, -0.0000, -0.0000],
        [-0.0000, -0.0000, -0.0000, -0.0000, -0.0000, -0.6472, -0.0000, -0.0000,
         -0.0000, -0.0000, -0.0000, -0.0000, -0.000

In [91]:
sum = prob_per_residue.sum(-1)
sum

tensor([-1.6401, -0.1096, -0.9372, -1.0919, -0.6472])

In [92]:
average_log_prob = sum.mean()
average_log_prob

tensor(-0.8852)

In [94]:
overall_confidence = torch.exp(average_log_prob)
overall_confidence

tensor(0.4126)

In [ ]:
data['mean_of_probs']

{'C1': {'A': 0.08523071,
  'C': 0.0071114027,
  'D': 0.02429955,
  'E': 0.044835098,
  'F': 0.012873793,
  'G': 0.11167856,
  'H': 0.24378654,
  'I': 0.01503631,
  'K': 0.030094158,
  'L': 0.030452648,
  'M': 0.09108686,
  'N': 0.026763206,
  'P': 0.06454336,
  'Q': 0.02387775,
  'R': 0.01883518,
  'S': 0.10755507,
  'T': 0.024905393,
  'V': 0.018390104,
  'W': 0.0056215376,
  'Y': 0.0077062473,
  'X': 0.005316492},
 'C2': {'A': 0.07080939,
  'C': 0.010389229,
  'D': 0.016589886,
  'E': 0.024992097,
  'F': 0.012113516,
  'G': 0.12308347,
  'H': 0.04186215,
  'I': 0.028428605,
  'K': 0.11870365,
  'L': 0.04828514,
  'M': 0.07955555,
  'N': 0.03307462,
  'P': 0.024371093,
  'Q': 0.032277107,
  'R': 0.10434858,
  'S': 0.089603886,
  'T': 0.07546203,
  'V': 0.046567533,
  'W': 0.0060088504,
  'Y': 0.008781867,
  'X': 0.0046917666},
 'C3': {'A': 0.030095711,
  'C': 0.005987605,
  'D': 0.02584773,
  'E': 0.034484066,
  'F': 0.005220192,
  'G': 0.0066746413,
  'H': 0.009555725,
  'I': 0.00428

In [5]:
import torch

def overall_confidence_from_score_pt(pt_path: str):
    d = torch.load(pt_path, map_location="cpu")
    # inputs from score.py
    log_probs = torch.tensor(d["log_probs"], dtype=torch.float32)  # [N, L, 21]
    native_seq = torch.tensor(d["native_sequence"], dtype=torch.long)  # [L]
    mask = torch.tensor(d["mask"], dtype=torch.float32)  # [L]
    chain_mask = torch.tensor(d["chain_mask"], dtype=torch.float32)  # [L]
    m = mask * chain_mask  # [L]

    # broadcast native sequence across all samples N
    N, L, _ = log_probs.shape
    S_one_hot = torch.nn.functional.one_hot(native_seq, num_classes=21).float()  # [L, 21]
    S_one_hot = S_one_hot.unsqueeze(0).repeat(N, 1, 1)  # [N, L, 21]

    loss_per_pos = -(S_one_hot * log_probs).sum(-1)  # [N, L]
    loss = (loss_per_pos * m).sum(-1) / (m.sum() + 1e-8)  # [N]
    overall_confidence = torch.exp(-loss)  # [N]
    return overall_confidence.mean()  # scalar

In [6]:
overall_confidence_from_score_pt('/home/junjiechen/1_work/250401-Dpepalign/LigandMPNN/test_design_numbers/2000-0.1T/ligandmpnn_v_32_020_25/score_0.1/1a0n_1.pt')

tensor(0.2297)